### ISSUE TITLE
pkgconf 1.0.1 is out and other things

### ISSUE THREAD

**Issue by kaniini** [OpenMandrivaAssociation/pkgconf#1]
Hello!

pkgconf 1.0.1 is out, so please update as it includes `--print-provides` which you guys requested.

While looking at your specfile, I noticed a few things:

```
%configure \
        --with-system-includedir=%{_includedir} \
        --with-system-libdir="/usr/lib:%{_libdir}"
```

For these options you should probably query GCC to get the information.  Normally something like this is done:

```
turtle:~# gcc -print-search-dirs | grep libraries | cut -d'=' -f2 | sed -e's/:/\n/g' | xargs -n1 readlink -f | grep -v gcc | LC_ALL=C sort -u | tr '\n' : | sed 's/:$/\n/'
/lib:/usr/lib:/usr/x86_64-alpine-linux-musl/lib
```

Translating that into an rpm specfile is unfortunately beyond my abilities anymore (haven't touched an RPM system in a decade really).  `--with-system-includedir` needs to be the default include paths of the compiler, I'm not sure if `%{_includedir}` is appropriate there.

Correcting those issues should allow you to run `make check` as part of your `%check` phase.

**Comment by tpgxyz** [comment]
@kaniini Thanks, i've already updated pkgconf to 1.0.1 and it is currently build.

Speaking about you suggestion, we are using everywhere macros from RPM, so if we call gcc (we are using LLVM/clang by default ;) in return we gat same what %{_libdir} returns.

**Comment by kaniini** [comment]
okay.  can we check testsuite then?  maybe it's not an issue anymore :)

i'll bring up an openmandriva box this weekend and play with it.

**Comment by tpgxyz** [comment]
New build is running.

**Comment by tpgxyz** [comment]
Tests finished without any problems:

Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.17312
+ umask 022
+ cd /builddir/build/BUILD
+ cd pkgconf-1.0.1
+ '[' 1 -eq 1 ']'
+ make check
/bin/sh tests/run.sh ./pkgconf
........................................................................................................
104 tests done. All succeeded.
+ exit 0


See for more details
https://abf.openmandriva.org/build_lists/78424

**Comment by kaniini** [comment]
Awesome.  Looks like everything is good then!

**Comment by tpgxyz** [comment]
@kaniini Yes, thank you very much ! Looking for a credit to OpenMandriva on pkgconf :)
